
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FocusSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FocusSession
 * 
 */
export type FocusSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$FocusSessionPayload>

export type AggregateFocusSession = {
  _count: FocusSessionCountAggregateOutputType | null
  _avg: FocusSessionAvgAggregateOutputType | null
  _sum: FocusSessionSumAggregateOutputType | null
  _min: FocusSessionMinAggregateOutputType | null
  _max: FocusSessionMaxAggregateOutputType | null
}

export type FocusSessionAvgAggregateOutputType = {
  duration: number | null
}

export type FocusSessionSumAggregateOutputType = {
  duration: number | null
}

export type FocusSessionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  duration: number | null
  focusMode: string | null
  startedAt: Date | null
  endedAt: Date | null
  notes: string | null
  isCompleted: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FocusSessionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  duration: number | null
  focusMode: string | null
  startedAt: Date | null
  endedAt: Date | null
  notes: string | null
  isCompleted: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FocusSessionCountAggregateOutputType = {
  id: number
  userId: number
  title: number
  duration: number
  focusMode: number
  startedAt: number
  endedAt: number
  notes: number
  isCompleted: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FocusSessionAvgAggregateInputType = {
  duration?: true
}

export type FocusSessionSumAggregateInputType = {
  duration?: true
}

export type FocusSessionMinAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  duration?: true
  focusMode?: true
  startedAt?: true
  endedAt?: true
  notes?: true
  isCompleted?: true
  createdAt?: true
  updatedAt?: true
}

export type FocusSessionMaxAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  duration?: true
  focusMode?: true
  startedAt?: true
  endedAt?: true
  notes?: true
  isCompleted?: true
  createdAt?: true
  updatedAt?: true
}

export type FocusSessionCountAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  duration?: true
  focusMode?: true
  startedAt?: true
  endedAt?: true
  notes?: true
  isCompleted?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FocusSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusSession to aggregate.
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessions to fetch.
   */
  orderBy?: Prisma.FocusSessionOrderByWithRelationInput | Prisma.FocusSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FocusSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FocusSessions
  **/
  _count?: true | FocusSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FocusSessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FocusSessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FocusSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FocusSessionMaxAggregateInputType
}

export type GetFocusSessionAggregateType<T extends FocusSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateFocusSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFocusSession[P]>
    : Prisma.GetScalarType<T[P], AggregateFocusSession[P]>
}




export type FocusSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FocusSessionWhereInput
  orderBy?: Prisma.FocusSessionOrderByWithAggregationInput | Prisma.FocusSessionOrderByWithAggregationInput[]
  by: Prisma.FocusSessionScalarFieldEnum[] | Prisma.FocusSessionScalarFieldEnum
  having?: Prisma.FocusSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FocusSessionCountAggregateInputType | true
  _avg?: FocusSessionAvgAggregateInputType
  _sum?: FocusSessionSumAggregateInputType
  _min?: FocusSessionMinAggregateInputType
  _max?: FocusSessionMaxAggregateInputType
}

export type FocusSessionGroupByOutputType = {
  id: string
  userId: string
  title: string
  duration: number
  focusMode: string | null
  startedAt: Date
  endedAt: Date | null
  notes: string | null
  isCompleted: boolean
  createdAt: Date
  updatedAt: Date
  _count: FocusSessionCountAggregateOutputType | null
  _avg: FocusSessionAvgAggregateOutputType | null
  _sum: FocusSessionSumAggregateOutputType | null
  _min: FocusSessionMinAggregateOutputType | null
  _max: FocusSessionMaxAggregateOutputType | null
}

type GetFocusSessionGroupByPayload<T extends FocusSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FocusSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FocusSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FocusSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FocusSessionGroupByOutputType[P]>
      }
    >
  >



export type FocusSessionWhereInput = {
  AND?: Prisma.FocusSessionWhereInput | Prisma.FocusSessionWhereInput[]
  OR?: Prisma.FocusSessionWhereInput[]
  NOT?: Prisma.FocusSessionWhereInput | Prisma.FocusSessionWhereInput[]
  id?: Prisma.StringFilter<"FocusSession"> | string
  userId?: Prisma.StringFilter<"FocusSession"> | string
  title?: Prisma.StringFilter<"FocusSession"> | string
  duration?: Prisma.IntFilter<"FocusSession"> | number
  focusMode?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusSession"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  isCompleted?: Prisma.BoolFilter<"FocusSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FocusSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  focusMode?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type FocusSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FocusSessionWhereInput | Prisma.FocusSessionWhereInput[]
  OR?: Prisma.FocusSessionWhereInput[]
  NOT?: Prisma.FocusSessionWhereInput | Prisma.FocusSessionWhereInput[]
  userId?: Prisma.StringFilter<"FocusSession"> | string
  title?: Prisma.StringFilter<"FocusSession"> | string
  duration?: Prisma.IntFilter<"FocusSession"> | number
  focusMode?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusSession"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  isCompleted?: Prisma.BoolFilter<"FocusSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type FocusSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  focusMode?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FocusSessionCountOrderByAggregateInput
  _avg?: Prisma.FocusSessionAvgOrderByAggregateInput
  _max?: Prisma.FocusSessionMaxOrderByAggregateInput
  _min?: Prisma.FocusSessionMinOrderByAggregateInput
  _sum?: Prisma.FocusSessionSumOrderByAggregateInput
}

export type FocusSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.FocusSessionScalarWhereWithAggregatesInput | Prisma.FocusSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.FocusSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FocusSessionScalarWhereWithAggregatesInput | Prisma.FocusSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FocusSession"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FocusSession"> | string
  title?: Prisma.StringWithAggregatesFilter<"FocusSession"> | string
  duration?: Prisma.IntWithAggregatesFilter<"FocusSession"> | number
  focusMode?: Prisma.StringNullableWithAggregatesFilter<"FocusSession"> | string | null
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"FocusSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"FocusSession"> | Date | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"FocusSession"> | string | null
  isCompleted?: Prisma.BoolWithAggregatesFilter<"FocusSession"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FocusSession"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FocusSession"> | Date | string
}

export type FocusSessionCreateInput = {
  id?: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
}

export type FocusSessionUncheckedCreateInput = {
  id?: string
  userId: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FocusSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
}

export type FocusSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionCreateManyInput = {
  id?: string
  userId: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FocusSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionListRelationFilter = {
  every?: Prisma.FocusSessionWhereInput
  some?: Prisma.FocusSessionWhereInput
  none?: Prisma.FocusSessionWhereInput
}

export type FocusSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FocusSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  focusMode?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FocusSessionAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type FocusSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  focusMode?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FocusSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  focusMode?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isCompleted?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FocusSessionSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type FocusSessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput> | Prisma.FocusSessionCreateWithoutUserInput[] | Prisma.FocusSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusSessionCreateOrConnectWithoutUserInput | Prisma.FocusSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FocusSessionCreateManyUserInputEnvelope
  connect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
}

export type FocusSessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput> | Prisma.FocusSessionCreateWithoutUserInput[] | Prisma.FocusSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusSessionCreateOrConnectWithoutUserInput | Prisma.FocusSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FocusSessionCreateManyUserInputEnvelope
  connect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
}

export type FocusSessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput> | Prisma.FocusSessionCreateWithoutUserInput[] | Prisma.FocusSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusSessionCreateOrConnectWithoutUserInput | Prisma.FocusSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FocusSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.FocusSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FocusSessionCreateManyUserInputEnvelope
  set?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  delete?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  connect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  update?: Prisma.FocusSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.FocusSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FocusSessionUpdateManyWithWhereWithoutUserInput | Prisma.FocusSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FocusSessionScalarWhereInput | Prisma.FocusSessionScalarWhereInput[]
}

export type FocusSessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput> | Prisma.FocusSessionCreateWithoutUserInput[] | Prisma.FocusSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusSessionCreateOrConnectWithoutUserInput | Prisma.FocusSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FocusSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.FocusSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FocusSessionCreateManyUserInputEnvelope
  set?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  delete?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  connect?: Prisma.FocusSessionWhereUniqueInput | Prisma.FocusSessionWhereUniqueInput[]
  update?: Prisma.FocusSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.FocusSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FocusSessionUpdateManyWithWhereWithoutUserInput | Prisma.FocusSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FocusSessionScalarWhereInput | Prisma.FocusSessionScalarWhereInput[]
}

export type FocusSessionCreateWithoutUserInput = {
  id?: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FocusSessionUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FocusSessionCreateOrConnectWithoutUserInput = {
  where: Prisma.FocusSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput>
}

export type FocusSessionCreateManyUserInputEnvelope = {
  data: Prisma.FocusSessionCreateManyUserInput | Prisma.FocusSessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FocusSessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FocusSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.FocusSessionUpdateWithoutUserInput, Prisma.FocusSessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FocusSessionCreateWithoutUserInput, Prisma.FocusSessionUncheckedCreateWithoutUserInput>
}

export type FocusSessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FocusSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.FocusSessionUpdateWithoutUserInput, Prisma.FocusSessionUncheckedUpdateWithoutUserInput>
}

export type FocusSessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FocusSessionScalarWhereInput
  data: Prisma.XOR<Prisma.FocusSessionUpdateManyMutationInput, Prisma.FocusSessionUncheckedUpdateManyWithoutUserInput>
}

export type FocusSessionScalarWhereInput = {
  AND?: Prisma.FocusSessionScalarWhereInput | Prisma.FocusSessionScalarWhereInput[]
  OR?: Prisma.FocusSessionScalarWhereInput[]
  NOT?: Prisma.FocusSessionScalarWhereInput | Prisma.FocusSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"FocusSession"> | string
  userId?: Prisma.StringFilter<"FocusSession"> | string
  title?: Prisma.StringFilter<"FocusSession"> | string
  duration?: Prisma.IntFilter<"FocusSession"> | number
  focusMode?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  startedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusSession"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"FocusSession"> | string | null
  isCompleted?: Prisma.BoolFilter<"FocusSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FocusSession"> | Date | string
}

export type FocusSessionCreateManyUserInput = {
  id?: string
  title: string
  duration: number
  focusMode?: string | null
  startedAt: Date | string
  endedAt?: Date | string | null
  notes?: string | null
  isCompleted?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FocusSessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  focusMode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FocusSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  duration?: boolean
  focusMode?: boolean
  startedAt?: boolean
  endedAt?: boolean
  notes?: boolean
  isCompleted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSession"]>

export type FocusSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  duration?: boolean
  focusMode?: boolean
  startedAt?: boolean
  endedAt?: boolean
  notes?: boolean
  isCompleted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSession"]>

export type FocusSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  duration?: boolean
  focusMode?: boolean
  startedAt?: boolean
  endedAt?: boolean
  notes?: boolean
  isCompleted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSession"]>

export type FocusSessionSelectScalar = {
  id?: boolean
  userId?: boolean
  title?: boolean
  duration?: boolean
  focusMode?: boolean
  startedAt?: boolean
  endedAt?: boolean
  notes?: boolean
  isCompleted?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FocusSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "title" | "duration" | "focusMode" | "startedAt" | "endedAt" | "notes" | "isCompleted" | "createdAt" | "updatedAt", ExtArgs["result"]["focusSession"]>
export type FocusSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FocusSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FocusSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FocusSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FocusSession"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    title: string
    duration: number
    focusMode: string | null
    startedAt: Date
    endedAt: Date | null
    notes: string | null
    isCompleted: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["focusSession"]>
  composites: {}
}

export type FocusSessionGetPayload<S extends boolean | null | undefined | FocusSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload, S>

export type FocusSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FocusSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FocusSessionCountAggregateInputType | true
  }

export interface FocusSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FocusSession'], meta: { name: 'FocusSession' } }
  /**
   * Find zero or one FocusSession that matches the filter.
   * @param {FocusSessionFindUniqueArgs} args - Arguments to find a FocusSession
   * @example
   * // Get one FocusSession
   * const focusSession = await prisma.focusSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FocusSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, FocusSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FocusSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FocusSessionFindUniqueOrThrowArgs} args - Arguments to find a FocusSession
   * @example
   * // Get one FocusSession
   * const focusSession = await prisma.focusSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FocusSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FocusSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionFindFirstArgs} args - Arguments to find a FocusSession
   * @example
   * // Get one FocusSession
   * const focusSession = await prisma.focusSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FocusSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, FocusSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionFindFirstOrThrowArgs} args - Arguments to find a FocusSession
   * @example
   * // Get one FocusSession
   * const focusSession = await prisma.focusSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FocusSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FocusSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FocusSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FocusSessions
   * const focusSessions = await prisma.focusSession.findMany()
   * 
   * // Get first 10 FocusSessions
   * const focusSessions = await prisma.focusSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const focusSessionWithIdOnly = await prisma.focusSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FocusSessionFindManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FocusSession.
   * @param {FocusSessionCreateArgs} args - Arguments to create a FocusSession.
   * @example
   * // Create one FocusSession
   * const FocusSession = await prisma.focusSession.create({
   *   data: {
   *     // ... data to create a FocusSession
   *   }
   * })
   * 
   */
  create<T extends FocusSessionCreateArgs>(args: Prisma.SelectSubset<T, FocusSessionCreateArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FocusSessions.
   * @param {FocusSessionCreateManyArgs} args - Arguments to create many FocusSessions.
   * @example
   * // Create many FocusSessions
   * const focusSession = await prisma.focusSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FocusSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FocusSessions and returns the data saved in the database.
   * @param {FocusSessionCreateManyAndReturnArgs} args - Arguments to create many FocusSessions.
   * @example
   * // Create many FocusSessions
   * const focusSession = await prisma.focusSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FocusSessions and only return the `id`
   * const focusSessionWithIdOnly = await prisma.focusSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FocusSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FocusSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FocusSession.
   * @param {FocusSessionDeleteArgs} args - Arguments to delete one FocusSession.
   * @example
   * // Delete one FocusSession
   * const FocusSession = await prisma.focusSession.delete({
   *   where: {
   *     // ... filter to delete one FocusSession
   *   }
   * })
   * 
   */
  delete<T extends FocusSessionDeleteArgs>(args: Prisma.SelectSubset<T, FocusSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FocusSession.
   * @param {FocusSessionUpdateArgs} args - Arguments to update one FocusSession.
   * @example
   * // Update one FocusSession
   * const focusSession = await prisma.focusSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FocusSessionUpdateArgs>(args: Prisma.SelectSubset<T, FocusSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FocusSessions.
   * @param {FocusSessionDeleteManyArgs} args - Arguments to filter FocusSessions to delete.
   * @example
   * // Delete a few FocusSessions
   * const { count } = await prisma.focusSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FocusSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FocusSessions
   * const focusSession = await prisma.focusSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FocusSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, FocusSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusSessions and returns the data updated in the database.
   * @param {FocusSessionUpdateManyAndReturnArgs} args - Arguments to update many FocusSessions.
   * @example
   * // Update many FocusSessions
   * const focusSession = await prisma.focusSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FocusSessions and only return the `id`
   * const focusSessionWithIdOnly = await prisma.focusSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FocusSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FocusSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FocusSession.
   * @param {FocusSessionUpsertArgs} args - Arguments to update or create a FocusSession.
   * @example
   * // Update or create a FocusSession
   * const focusSession = await prisma.focusSession.upsert({
   *   create: {
   *     // ... data to create a FocusSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FocusSession we want to update
   *   }
   * })
   */
  upsert<T extends FocusSessionUpsertArgs>(args: Prisma.SelectSubset<T, FocusSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FocusSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionCountArgs} args - Arguments to filter FocusSessions to count.
   * @example
   * // Count the number of FocusSessions
   * const count = await prisma.focusSession.count({
   *   where: {
   *     // ... the filter for the FocusSessions we want to count
   *   }
   * })
  **/
  count<T extends FocusSessionCountArgs>(
    args?: Prisma.Subset<T, FocusSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FocusSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FocusSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FocusSessionAggregateArgs>(args: Prisma.Subset<T, FocusSessionAggregateArgs>): Prisma.PrismaPromise<GetFocusSessionAggregateType<T>>

  /**
   * Group by FocusSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FocusSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FocusSessionGroupByArgs['orderBy'] }
      : { orderBy?: FocusSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FocusSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFocusSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FocusSession model
 */
readonly fields: FocusSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FocusSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FocusSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FocusSession model
 */
export interface FocusSessionFieldRefs {
  readonly id: Prisma.FieldRef<"FocusSession", 'String'>
  readonly userId: Prisma.FieldRef<"FocusSession", 'String'>
  readonly title: Prisma.FieldRef<"FocusSession", 'String'>
  readonly duration: Prisma.FieldRef<"FocusSession", 'Int'>
  readonly focusMode: Prisma.FieldRef<"FocusSession", 'String'>
  readonly startedAt: Prisma.FieldRef<"FocusSession", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"FocusSession", 'DateTime'>
  readonly notes: Prisma.FieldRef<"FocusSession", 'String'>
  readonly isCompleted: Prisma.FieldRef<"FocusSession", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FocusSession", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FocusSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FocusSession findUnique
 */
export type FocusSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter, which FocusSession to fetch.
   */
  where: Prisma.FocusSessionWhereUniqueInput
}

/**
 * FocusSession findUniqueOrThrow
 */
export type FocusSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter, which FocusSession to fetch.
   */
  where: Prisma.FocusSessionWhereUniqueInput
}

/**
 * FocusSession findFirst
 */
export type FocusSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter, which FocusSession to fetch.
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessions to fetch.
   */
  orderBy?: Prisma.FocusSessionOrderByWithRelationInput | Prisma.FocusSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusSessions.
   */
  cursor?: Prisma.FocusSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusSessions.
   */
  distinct?: Prisma.FocusSessionScalarFieldEnum | Prisma.FocusSessionScalarFieldEnum[]
}

/**
 * FocusSession findFirstOrThrow
 */
export type FocusSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter, which FocusSession to fetch.
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessions to fetch.
   */
  orderBy?: Prisma.FocusSessionOrderByWithRelationInput | Prisma.FocusSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusSessions.
   */
  cursor?: Prisma.FocusSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusSessions.
   */
  distinct?: Prisma.FocusSessionScalarFieldEnum | Prisma.FocusSessionScalarFieldEnum[]
}

/**
 * FocusSession findMany
 */
export type FocusSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessions to fetch.
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessions to fetch.
   */
  orderBy?: Prisma.FocusSessionOrderByWithRelationInput | Prisma.FocusSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FocusSessions.
   */
  cursor?: Prisma.FocusSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessions.
   */
  skip?: number
  distinct?: Prisma.FocusSessionScalarFieldEnum | Prisma.FocusSessionScalarFieldEnum[]
}

/**
 * FocusSession create
 */
export type FocusSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a FocusSession.
   */
  data: Prisma.XOR<Prisma.FocusSessionCreateInput, Prisma.FocusSessionUncheckedCreateInput>
}

/**
 * FocusSession createMany
 */
export type FocusSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FocusSessions.
   */
  data: Prisma.FocusSessionCreateManyInput | Prisma.FocusSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FocusSession createManyAndReturn
 */
export type FocusSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * The data used to create many FocusSessions.
   */
  data: Prisma.FocusSessionCreateManyInput | Prisma.FocusSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FocusSession update
 */
export type FocusSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a FocusSession.
   */
  data: Prisma.XOR<Prisma.FocusSessionUpdateInput, Prisma.FocusSessionUncheckedUpdateInput>
  /**
   * Choose, which FocusSession to update.
   */
  where: Prisma.FocusSessionWhereUniqueInput
}

/**
 * FocusSession updateMany
 */
export type FocusSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FocusSessions.
   */
  data: Prisma.XOR<Prisma.FocusSessionUpdateManyMutationInput, Prisma.FocusSessionUncheckedUpdateManyInput>
  /**
   * Filter which FocusSessions to update
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * Limit how many FocusSessions to update.
   */
  limit?: number
}

/**
 * FocusSession updateManyAndReturn
 */
export type FocusSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * The data used to update FocusSessions.
   */
  data: Prisma.XOR<Prisma.FocusSessionUpdateManyMutationInput, Prisma.FocusSessionUncheckedUpdateManyInput>
  /**
   * Filter which FocusSessions to update
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * Limit how many FocusSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FocusSession upsert
 */
export type FocusSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the FocusSession to update in case it exists.
   */
  where: Prisma.FocusSessionWhereUniqueInput
  /**
   * In case the FocusSession found by the `where` argument doesn't exist, create a new FocusSession with this data.
   */
  create: Prisma.XOR<Prisma.FocusSessionCreateInput, Prisma.FocusSessionUncheckedCreateInput>
  /**
   * In case the FocusSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FocusSessionUpdateInput, Prisma.FocusSessionUncheckedUpdateInput>
}

/**
 * FocusSession delete
 */
export type FocusSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
  /**
   * Filter which FocusSession to delete.
   */
  where: Prisma.FocusSessionWhereUniqueInput
}

/**
 * FocusSession deleteMany
 */
export type FocusSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusSessions to delete
   */
  where?: Prisma.FocusSessionWhereInput
  /**
   * Limit how many FocusSessions to delete.
   */
  limit?: number
}

/**
 * FocusSession without action
 */
export type FocusSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSession
   */
  select?: Prisma.FocusSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSession
   */
  omit?: Prisma.FocusSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionInclude<ExtArgs> | null
}
